export const ADDRESS_ACTION_TYPES = {
    FETCH_ADDRESS_START:'FETCH_ADDRESS_START',
    FETCH_ADDRESS_SUCCESS:'FETCH_ADDRESS_SUCCESS',
    FETCH_ADDRESS_FAILED:'FETCH_ADDRESS_FAILED',
    ADD_ADDRESS_START:'ADD_ADDRESS_START',
    ADD_ADDRESS_SUCCESS:'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAILED:'ADD_ADDRESS_FAILED',
    DELETE_ADDRESS_START:'DELETE_ADDRESS_START',
    DELETE_ADDRESS_SUCCESS:'DELETE_ADDRESS_SUCCESS',
    DELETE_ADDRESS_FAILED:'DELETE_ADDRESS_FAILED',
}