export const CART_ACTION_TYPE = {
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
    FETCH_CART_ITEMS_START: 'FETCH_CART_ITEMS_START',
    FETCH_CART_ITEMS_SUCCESS: 'FETCH_CART_ITEMS_SUCCESS',
    FETCH_CART_ITEMS_FAILED: 'FETCH_CART_ITEMS_FAILED',
    SET_CART_ITEMS_START: 'SET_CART_ITEMS_START',
    SET_CART_ITEMS_SUCCESS: 'SET_CART_ITEMS_SUCCESS',
    SET_CART_ITEMS_FAILED: 'SET_CART_ITEMS_FAILED',
    ADD_CART_ITEMS: 'ADD_CART_ITEMS',
    REMOVE_CART_ITEMS: 'REMOVE_CART_ITEMS',
    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
    SIGN_OUT_CART_ITEMS: 'SIGN_OUT_CART_ITEMS'
}